"""
blog admin page generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.contrib import admin
from blog.models import Blog


class BlogAdmin(admin.ModelAdmin):
	"""docstring for BlogAdmin"""
	list_display = (
		'text', 
		'created_datetime',
		'updated_datetime',
	)
		

admin.site.register(Blog, BlogAdmin)
