"""
blog forms generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django import forms
from blog.models import Blog


class BlogModelForm(forms.ModelForm):
	"""
	model form using Blog model
	"""
	class Meta:
		model = Blog
		fields = (
			'text',
		)


class BlogForm(forms.Form):
	"""
	form using Blog model
	"""
	text = forms.CharField(widget=forms.Textarea)

