"""
blog admin page generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.db import models
from django.core.urlresolvers import reverse_lazy as reverse
from django.utils.translation import ugettext as _


class Blog(models.Model):
    """
    blog template model
    """

    text = models.CharField(
        _("text"),
        max_length=20)

    created_datetime = models.DateTimeField(
        _("created datetime"),
        auto_now_add=True)

    updated_datetime = models.DateTimeField(
        _("updated datetime"),
        auto_now=True)

    def get_absolute_url(self):
        """
        return detail page url
        """
        return reverse('blog_detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        """
        <CAUTION>
        this will be used to indicate a model object.
        it should never be long that 200 charactor when you use admin!
        """
        return "<Blog Object>"

    class Meta:
        """
        <Usually used meta options>
        """
        ordering = (
            "created_datetime",
        )
        get_latest_by = "created_datetime"
