"""
blog test cases generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.test import TestCase
from django.core.urlresolvers import reverse

# Create your tests here.

class BlogCRUDTestCase(TestCase):
    """
    testcases for BlogCRUDTestCase
    """
    def setUp(self):
        pass

    def test_create_blog(self):
        """
        post to test_create_blog
        """
        response = self.client.post(
            reverse('blog_create'),
            { 
                "text": "test comment", 
            },
            follow=True,
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['object'].text, "test comment")
        self.assertTemplateUsed(response, 'blog/detail.html')
		
    def test_detail_blog(self):
        """
        get to test_detail_blog
        """
        pass

    def test_update_blog(self):
        """
        post to test_update_blog
        """
        pass

    def test_list_blog(self):
        """
        get to test_list_blog
        """
        pass

    def test_delete_blog(self):
        """
        post to test_delete_blog
        """
        pass

