"""
blog url configure generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.conf.urls import patterns, include, url
from blog import views as blog_views

urlpatterns = patterns(
    '',

    #
    # A Basic CRUD function for Blog model
    #
    # List all objects of Blog
    url(r'^$',
        blog_views.BlogListView.as_view(),
        name="blog_list"),

    # Create new object of Blog
    url(r'^create$',
        blog_views.BlogCreateView.as_view(),
        name="blog_create"),

    # Delete an object of Blog
    url(r'^(?P<pk>[a-z0-9A-Z]+)/delete$',
        blog_views.BlogDeleteView.as_view(),
        name="blog_delete"),

    # Update an object of Blog
    url(r'^(?P<pk>[a-z0-9A-Z]+)/update$',
        blog_views.BlogUpdateView.as_view(),
        name="blog_update"),

    # Details of a object of Blog
    url(r'^(?P<pk>[a-z0-9A-Z]+)$',
        blog_views.BlogDetailView.as_view(),
        name="blog_detail"),

)

