"""
blog views generated by template

template author: Meng Zhao fortable1999@gmail.com

A basic CRUD viewset is defined.
"""

from django.core.urlresolvers import reverse_lazy as reverse
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.shortcuts import render

from blog.models import Blog
from blog.forms import BlogModelForm


class BlogListView(ListView):
	template_name = "blog/list.html"
	model = Blog


class BlogCreateView(CreateView):
	template_name = "blog/create.html"
	form_class = BlogModelForm

	def get_success_url(self):
		return reverse('blog_detail', kwargs={'pk': self.object.id})


class BlogDetailView(DetailView):
	template_name = "blog/detail.html"
	model = Blog


class BlogDeleteView(DeleteView):
	template_name = "blog/delete.html"
	form_class = BlogModelForm
	model = Blog

	def get_success_url(self):
		return reverse('blog_list')


class BlogUpdateView(UpdateView):
	template_name = "blog/update.html"
	form_class = BlogModelForm
	model = Blog

	def get_success_url(self):
		return reverse('blog_detail', kwargs={'pk': self.object.id})
