"""
compare admin page generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.contrib import admin
from compare.models import Compare


class CompareAdmin(admin.ModelAdmin):
	"""docstring for CompareAdmin"""
	list_display = (
		'dmm_id1', 
		'dmm_id2', 
		'created_datetime',
		'updated_datetime',
	)
		

admin.site.register(Compare, CompareAdmin)
