"""
compare forms generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django import forms
from django.utils.translation import ugettext as _

from compare.models import Compare


class CompareModelForm(forms.ModelForm):
	"""
	model form using Compare model
	"""
	class Meta:
		model = Compare
		fields = (
			'dmm_id1',
			'dmm_id2',
		)


VOTE_CHOICES = (
	(0, _("first one")),
	(1, _("second one")),
)

class VoteForm(forms.Form):
	choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=VOTE_CHOICES)

