"""
compare admin page generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.db import models
from django.core.urlresolvers import reverse_lazy as reverse
from django.utils.translation import ugettext as _


class Compare(models.Model):
	"""
	compare template model
	"""

	dmm_id1 = models.CharField(
			_("dmm id 1"),
			max_length=20)

	dmm_id2 = models.CharField(
			_("dmm id 2"),
			max_length=20)

	dmm_count1 = models.IntegerField(
			_('dmm count 1'), default=0)

	dmm_count2 = models.IntegerField(
			_('dmm count 2'), default=0)

	created_datetime = models.DateTimeField(
			_("created datetime"),
			auto_now_add=True)

	updated_datetime = models.DateTimeField(
			_("updated datetime"),
			auto_now=True)

	def get_absolute_url(self):
		"""
		return detail page url
		"""
		return reverse('compare', kwargs={'id1': self.dmm_id1, 'id2':self.dmm_id2})

	def __unicode__(self):
		"""
		<CAUTION>
		this will be used to indicate a model object.
		it should never be long that 200 charactor when you use admin!
		"""
		return "<Compare Object>"

	class Meta:
		"""
		<Usually used meta options>
		"""
		ordering = (
			"created_datetime",
		)
		get_latest_by = "created_datetime"
