"""
compare test cases generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.test import TestCase
from django.core.urlresolvers import reverse

# Create your tests here.

class CompareCRUDTestCase(TestCase):
    """
    testcases for CompareCRUDTestCase
    """
    def setUp(self):
        pass

    def test_create_compare(self):
        """
        post to test_create_compare
        """
        response = self.client.post(
            reverse('compare_create'),
            { 
                "text": "test comment", 
            },
            follow=True,
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['object'].text, "test comment")
        self.assertTemplateUsed(response, 'compare/detail.html')
		
    def test_detail_compare(self):
        """
        get to test_detail_compare
        """
        pass

    def test_update_compare(self):
        """
        post to test_update_compare
        """
        pass

    def test_list_compare(self):
        """
        get to test_list_compare
        """
        pass

    def test_delete_compare(self):
        """
        post to test_delete_compare
        """
        pass

