"""
compare url configure generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.conf.urls import patterns, include, url
from compare import views as compare_views

urlpatterns = patterns(
    '',

    url(r'^list$',
        compare_views.CompareListView.as_view(),
        name="compare_list"),

    url(r'^create$',
        compare_views.CompareCreateView.as_view(),
        name="compare_create"),

    url(r'^details/(?P<compare_id>[0-9]+)$',
        compare_views.CompareDetailView.as_view(),
        name="compare_detail"),

    url(r'^vote/(?P<compare_id>[0-9]+)$',
        compare_views.VoteView.as_view(),
        name="compare_vote"),

)

