"""
compare views generated by template

template author: Meng Zhao fortable1999@gmail.com

A basic CRUD viewset is defined.
"""

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy as reverse
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, FormView
from django.shortcuts import render

from compare.models import Compare
from compare.forms import CompareModelForm, VoteForm


class CompareListView(ListView):
	template_name = "compare/list.html"
	model = Compare


class CompareCreateView(CreateView):
	template_name = "compare/create.html"
	form_class = CompareModelForm

	def get_success_url(self):
		return reverse('compare_detail', kwargs={'compare_id': self.object.id})


class CompareDetailView(DetailView):
	template_name = "compare/detail.html"
	model = Compare

	def get_context_data(self, **kwargs):
		context = super(CompareDetailView, self).get_context_data(**kwargs)
		vote_form = VoteForm()
		context.update({'form': vote_form})
		return context

	def get_object(self):
		pk = self.kwargs['compare_id']
		return self.model.objects.get(pk=pk)


class VoteView(FormView):
	http_method_names = ['post']

	form_class = VoteForm

	def form_valid(self, form):
		selected = form.cleaned_data['choice_field']
		object = Compare.objects.get(pk=self.kwargs['compare_id'])
		if selected == '0':
			object.dmm_count1 += 1
			object.save()
		if selected == '1':
			object.dmm_count2 += 1
			object.save()
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form):
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		object = Compare.objects.get(pk=self.kwargs['compare_id'])
		return reverse('compare_detail', kwargs={'compare_id': object.id})
